Do not build iso

diff --git a/.github/workflows/kickstart-tests.yml b/.github/workflows/kickstart-tests.yml
--- a/.github/workflows/kickstart-tests.yml
+++ b/.github/workflows/kickstart-tests.yml
@@ -209,43 +209,43 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build anaconda-iso-creator container image
-        working-directory: ./anaconda
-        run: |
-          # set static tag to avoid complications when looking what tag is used
-          sudo make -f ./Makefile.am anaconda-iso-creator-build CI_TAG=$CONTAINER_TAG
-
-      - name: Build anaconda-rpm container (for RPM build)
-        working-directory: ./anaconda
-        run: |
-          # set static tag to avoid complications when looking what tag is used
-          make -f ./Makefile.am anaconda-rpm-build CI_TAG=$CONTAINER_TAG
-
-      - name: Build Anaconda RPM files
-        working-directory: ./anaconda
-        run: |
-          # output of the build will be stored in ./result/build/01-rpm-build/*.rpm
-          make -f ./Makefile.am container-rpms-scratch CI_TAG=$CONTAINER_TAG
-          mkdir -p ${{ github.workspace }}/kickstart-tests/data/additional_repo/
-          cp -av ./result/build/01-rpm-build/*.rpm ${{ github.workspace }}/kickstart-tests/data/additional_repo/
-
-      - name: Build boot.iso
-        run: |
-          mkdir -p images
-          # /var/tmp tmpfs speeds up lorax and avoids https://bugzilla.redhat.com/show_bug.cgi?id=1906364
-          sudo podman run -i --rm --privileged \
-            --tmpfs /var/tmp:rw,mode=1777 \
-            -v ${{ github.workspace }}/kickstart-tests/data/additional_repo:/anaconda-rpms:ro \
-            -v ${{ github.workspace }}/images:/images:z \
-            $ISO_BUILD_CONTAINER_NAME:$CONTAINER_TAG
-
-      - name: Clean up after lorax
-        if: always()
-        run: |
-          # remove container images together with the container
-          sudo podman rmi -f $ISO_BUILD_CONTAINER_NAME:$CONTAINER_TAG || true
-          sudo podman rmi -f $RPM_BUILD_CONTAINER_NAME:$CONTAINER_TAG || true
-
+          #      - name: Build anaconda-iso-creator container image
+          #        working-directory: ./anaconda
+          #        run: |
+          #          # set static tag to avoid complications when looking what tag is used
+          #          sudo make -f ./Makefile.am anaconda-iso-creator-build CI_TAG=$CONTAINER_TAG
+          #
+          #      - name: Build anaconda-rpm container (for RPM build)
+          #        working-directory: ./anaconda
+          #        run: |
+          #          # set static tag to avoid complications when looking what tag is used
+          #          make -f ./Makefile.am anaconda-rpm-build CI_TAG=$CONTAINER_TAG
+          #
+          #      - name: Build Anaconda RPM files
+          #        working-directory: ./anaconda
+          #        run: |
+          #          # output of the build will be stored in ./result/build/01-rpm-build/*.rpm
+          #          make -f ./Makefile.am container-rpms-scratch CI_TAG=$CONTAINER_TAG
+          #          mkdir -p ${{ github.workspace }}/kickstart-tests/data/additional_repo/
+          #          cp -av ./result/build/01-rpm-build/*.rpm ${{ github.workspace }}/kickstart-tests/data/additional_repo/
+          #
+          #      - name: Build boot.iso
+          #        run: |
+          #          mkdir -p images
+          #          # /var/tmp tmpfs speeds up lorax and avoids https://bugzilla.redhat.com/show_bug.cgi?id=1906364
+          #          sudo podman run -i --rm --privileged \
+          #            --tmpfs /var/tmp:rw,mode=1777 \
+          #            -v ${{ github.workspace }}/kickstart-tests/data/additional_repo:/anaconda-rpms:ro \
+          #            -v ${{ github.workspace }}/images:/images:z \
+          #            $ISO_BUILD_CONTAINER_NAME:$CONTAINER_TAG
+          #
+          #      - name: Clean up after lorax
+          #        if: always()
+          #        run: |
+          #          # remove container images together with the container
+          #          sudo podman rmi -f $ISO_BUILD_CONTAINER_NAME:$CONTAINER_TAG || true
+          #          sudo podman rmi -f $RPM_BUILD_CONTAINER_NAME:$CONTAINER_TAG || true
+          #
       - name: Generate query arguments for "${{ needs.pr-info.outputs.launch_args }}"
         id: generate_query
         working-directory: ./kickstart-tests
