Do not generate the iso again when developing a test

diff --git a/.github/workflows/webui-tests.yml b/.github/workflows/webui-tests.yml
--- a/.github/workflows/webui-tests.yml
+++ b/.github/workflows/webui-tests.yml
@@ -147,44 +147,44 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build anaconda-rpm container (for RPM build)
-        working-directory: ./anaconda
-        run: |
-          # set static tag to avoid complications when looking what tag is used
-          make -f Makefile.am anaconda-rpm-build CI_TAG=$CONTAINER_TAG
-
-      - name: Build Anaconda RPM files
-        working-directory: ./anaconda
-        run: |
-          # output of the build will be stored in ./result/build/01-rpm-build/*.rpm
-          make -f Makefile.am container-rpms-scratch CI_TAG=$CONTAINER_TAG
-          mkdir -p ./anaconda_rpms/
-          cp -av ./result/build/01-rpm-build/*.rpm ./anaconda_rpms/
-
-      - name: Build anaconda-iso-creator container image
-        working-directory: ./anaconda
-        run: |
-          # set static tag to avoid complications when looking what tag is used
-          sudo make -f Makefile.am anaconda-iso-creator-build CI_TAG=$CONTAINER_TAG
-
-      - name: Build the boot.iso
-        working-directory: ./anaconda
-        run: |
-          mkdir -p images
-          # /var/tmp tmpfs speeds up lorax and avoids https://bugzilla.redhat.com/show_bug.cgi?id=1906364
-          sudo podman run -i --rm --privileged \
-            --tmpfs /var/tmp:rw,mode=1777 \
-            -v `pwd`/anaconda_rpms:/anaconda-rpms:ro \
-            -v `pwd`/images:/images:z \
-            --entrypoint /lorax-build-webui \
-            $ISO_BUILD_CONTAINER_NAME:$CONTAINER_TAG
-
-      - name: Clean up after lorax
-        if: always()
-        run: |
-          # remove container images together with the container
-          sudo podman rmi -f $ISO_BUILD_CONTAINER_NAME:$CONTAINER_TAG || true
-          sudo podman rmi -f $RPM_BUILD_CONTAINER_NAME:$CONTAINER_TAG || true
+            #      - name: Build anaconda-rpm container (for RPM build)
+            #        working-directory: ./anaconda
+            #        run: |
+            #          # set static tag to avoid complications when looking what tag is used
+            #          make -f Makefile.am anaconda-rpm-build CI_TAG=$CONTAINER_TAG
+            #
+            #      - name: Build Anaconda RPM files
+            #        working-directory: ./anaconda
+            #        run: |
+            #          # output of the build will be stored in ./result/build/01-rpm-build/*.rpm
+            #          make -f Makefile.am container-rpms-scratch CI_TAG=$CONTAINER_TAG
+            #          mkdir -p ./anaconda_rpms/
+            #          cp -av ./result/build/01-rpm-build/*.rpm ./anaconda_rpms/
+            #
+            #      - name: Build anaconda-iso-creator container image
+            #        working-directory: ./anaconda
+            #        run: |
+            #          # set static tag to avoid complications when looking what tag is used
+            #          sudo make -f Makefile.am anaconda-iso-creator-build CI_TAG=$CONTAINER_TAG
+            #
+            #      - name: Build the boot.iso
+            #        working-directory: ./anaconda
+            #        run: |
+            #          mkdir -p images
+            #          # /var/tmp tmpfs speeds up lorax and avoids https://bugzilla.redhat.com/show_bug.cgi?id=1906364
+            #          sudo podman run -i --rm --privileged \
+            #            --tmpfs /var/tmp:rw,mode=1777 \
+            #            -v `pwd`/anaconda_rpms:/anaconda-rpms:ro \
+            #            -v `pwd`/images:/images:z \
+            #            --entrypoint /lorax-build-webui \
+            #            $ISO_BUILD_CONTAINER_NAME:$CONTAINER_TAG
+            #
+            #      - name: Clean up after lorax
+            #        if: always()
+            #        run: |
+            #          # remove container images together with the container
+            #          sudo podman rmi -f $ISO_BUILD_CONTAINER_NAME:$CONTAINER_TAG || true
+            #          sudo podman rmi -f $RPM_BUILD_CONTAINER_NAME:$CONTAINER_TAG || true
 
       - name: Create Permian settings file
         working-directory: ./permian
@@ -221,7 +221,7 @@ jobs:
             run_event '{
               "type":"github.pr.anaconda",
               "bootIso": {
-                "x86_64": "file://${{ github.workspace }}/anaconda/images/boot.iso"
+                "x86_64": "http://cobra02/users/rv/webui_repo/boot.e2e.88.iso"
               }
             }'
 
@@ -239,14 +239,14 @@ jobs:
             permian/xunit*.xml
             permian/*.dump
 
-      - name: Upload image artifacts
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: images
-          path: |
-            anaconda/images/boot.iso
-
+            #      - name: Upload image artifacts
+            #        if: always()
+            #        uses: actions/upload-artifact@v3
+            #        with:
+            #          name: images
+            #          path: |
+            #            anaconda/images/boot.iso
+            #
       # Permian exit code doesn't reflect the test results
       - name: Check tests results
         working-directory: ./permian
